GET http://localhost:3000/contacts

###

GET http://localhost:3000/contacts/1

### 

POST http://localhost:3000/contacts
Content-Type: application/json

{
  "first_name" : "Kyle" ,
  "last_name" : "Walker" ,
  "address" : "601 Lakeside Ave E, Cleveland, OH 44114",
  "email" : "walker@gmail.com",
  "phone_number" : "444-999-8888"
}




